CREATE TABLE leitor
(
    id_leitor      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR(255),
    status         VARCHAR(255)                            NOT NULL,
    patio_id_patio BIGINT,
    CONSTRAINT pk_leitor PRIMARY KEY (id_leitor)
);

CREATE TABLE moto
(
    id_moto          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa            VARCHAR(255),
    modelo           VARCHAR(255),
    rfid_tag         VARCHAR(255),
    data_cadastro    date,
    servico          VARCHAR(255),
    leitor_id_leitor BIGINT,
    CONSTRAINT pk_moto PRIMARY KEY (id_moto)
);

CREATE TABLE movimento
(
    id_moviment      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_evento      date,
    patio_id_patio   BIGINT,
    leitor_id_leitor BIGINT,
    moto_id_moto     BIGINT,
    tipo_movimento   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_movimento PRIMARY KEY (id_moviment)
);

CREATE TABLE patio
(
    id_patio   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    endereco   VARCHAR(255),
    capacidade DOUBLE PRECISION,
    CONSTRAINT pk_patio PRIMARY KEY (id_patio)
);

ALTER TABLE leitor
    ADD CONSTRAINT FK_LEITOR_ON_PATIO_ID_PATIO FOREIGN KEY (patio_id_patio) REFERENCES patio (id_patio);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_LEITOR_ID_LEITOR FOREIGN KEY (leitor_id_leitor) REFERENCES leitor (id_leitor);

ALTER TABLE movimento
    ADD CONSTRAINT FK_MOVIMENTO_ON_LEITOR_ID_LEITOR FOREIGN KEY (leitor_id_leitor) REFERENCES leitor (id_leitor);

ALTER TABLE movimento
    ADD CONSTRAINT FK_MOVIMENTO_ON_MOTO_ID_MOTO FOREIGN KEY (moto_id_moto) REFERENCES moto (id_moto);

ALTER TABLE movimento
    ADD CONSTRAINT FK_MOVIMENTO_ON_PATIO_ID_PATIO FOREIGN KEY (patio_id_patio) REFERENCES patio (id_patio);