CREATE TABLE mottuser
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    email       VARCHAR(255) UNIQUE,
    avatar_url  VARCHAR(255),
    CONSTRAINT pk_mottuser PRIMARY KEY (id)
);

ALTER TABLE movimento
    ADD COLUMN user_id BIGINT;

ALTER TABLE movimento
    ADD CONSTRAINT FK_MOVIMENTO_ON_USER_ID FOREIGN KEY (user_id) REFERENCES mottuser (id);